name: Update DNS Record

on:
  workflow_dispatch:
    inputs:
      source_cname:
        description: 'Source CNAME Record'
        required: true
      destination_cname:
        description: 'Destination CNAME Record'
        required: true

jobs:
  update-dns:
    runs-on: DNS  # Make sure this matches the label of your self-hosted runner
    name: Update Route53 DNS Record
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Boto3
        run: |
          python -m pip install boto3
          
      - name: Update DNS Record
        env:
          AWS_REGION: 'us-east-1'  # Replace with the AWS region your Route 53 is hosted in, if it's different
          SOURCE_CNAME: ${{ github.event.inputs.source_cname }}
          DESTINATION_CNAME: ${{ github.event.inputs.destination_cname }}
        run: |
          python update_route53_dns.py
